### ISSUE TITLE
Дебаг

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-8-flowcharts#26]
При попытке дебага в правом столбце есть значение NaN, уберите его пожалуйста.

**Comment by coudam** [comment]
не баг, а фича. так должно быть. NaN отображается только при условии что нет инициализированных переменных до этого участка блока в дебаге

**Comment by Mazdaywik** [comment]
А почему reopen без объяснения причины?

**Comment by Lanaken** [comment]
случайность
